# Site settings
title: CMR User guides
email: felipe@crssoftware.co.nz
description: > 
    User guides to help you run a high performance farm with Cash Manager Rural
baseurl: "/cmr-guides" # the subpath of your site, e.g. /blog/
url: "http://felipeskroski.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty
slim:
  pretty: true
  format: html5
exclude: [
            package.json, 
            bower.json, 
            grunt.js,
            gruntfile.js, 
            node_modules, 
            bower_components,
            validation-report.json, 
            validation-status.json,
            scripts.js, 
            scripts.tmp.min.js,
            style.css,
            style.tmp.min.css,
            Makefile,
            Gemfile,
            Gemfile.lock,
            feed.xml,
            exclude.rsync,
            README.markdown
         ]

